version: '3.8'
services:
  gitea:
    image: gitea/gitea:latest
    environment:
      USER_UID: 1000
      USER_GID: 1000
    volumes:
      - ./gitea-data:/data
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db
      - redis
      - minio
      - elasticsearch

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: gitea_pass
      POSTGRES_DB: gitea
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    volumes:
      - ./redis-data:/data

  minio:
    image: minio/minio:latest
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - "9000:9000"
    volumes:
      - ./minio-data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  simulation:
    build: ./simulation
    depends_on:
      - redis
    ports:
      - "8000:8000"

  search:
    build: ./search
    depends_on:
      - elasticsearch
    ports:
      - "8080:8080"

  sms:
    build: ./sms
    environment:
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgresql://gitea:gitea_pass@db:5432/gitea
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"